import Head from "next/head";
import Features from "../components/Features";
import PizzaList from "../components/Pizzalist";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Features />
      <PizzaList />
    </div>
  );
}
